#!/usr/bin/env bash

function bootstrap {
  local shome="${_phoenix_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      sudo -E aptitude install -y inotify-tools
      ;;
  esac

  mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phoenix_new-1.2.1.ez
}

bootstrap
