#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      sudo aptitude update
      sudo aptitude install -y inotify-tools
      ;;
  esac

  mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez
}

bootstrap
