#!/usr/bin/env bash

function main {
  local shome="${_phoenix_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -n "$(mix archive 2>&- | awk '$1 == "*" && $2 ~ /^phoenix_new/ { print $2 }')" ]]; then
    return 1
  else
    return 0
  fi
}

source sub "$0" "$@"
