#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_phoenix="$(mix phoenix.new -v 2>&- | awk 'NR == 1 {print $2}' | perl -pe 's{^v}{}' || true)"
  jq -n --arg phoenix "$ver_phoenix" '{phoenix: $phoenix}'
}

version "$@"
